'use strict';

let sanitizedRoadWords = {
    'aly': 'alley',
    'ave': 'avenue',
    'bnd': 'bend',
    'btm': 'bottom',
    'blvd': 'boulevard',
    'brg': 'bridge',
    'bdwy': 'broadway',
    'cswy': 'causeway',
    'ctr': 'center',
    'ctrs': 'centers',
    'cct': 'circuit',
    'clf': 'cliff',
    'clfs': 'cliffs',
    'cl': 'close',
    'clb': 'club',
    'cmn': 'common',
    'cmns': 'commons',
    'cor': 'corner',
    'cors': 'corners',
    'ct': 'court',
    'cts': 'courts',
    'cv': 'cove',
    'cr': 'crescent',
    'crk': 'creek',
    'cres': 'crescent',
    'crst': 'crest',
    'xing': 'crossing',
    'xrd': 'crossroad',
    'dr': 'Drive',
    'est': 'Estate',
    'ests': 'Estates',
    'expy': 'expressway',
    'ft': 'fort',
    'fwy': 'freeway',
    'gdn': 'garden',
    'gdns': 'gardens',
    'gln': 'glen',
    'glns': 'glens',
    'grns': 'greens',
    'grv': 'grove',
    'grvs': 'groves',
    'hbr': 'harbor',
    'hbrs': 'harbors',
    'hvn': 'haven',
    'hts': 'heights',
    'hwy': 'highway',
    'hl': 'hill',
    'hls': 'hills',
    'holw': 'hollow',
    'lk': 'lake',
    'lks': 'lakes',
    'ln': 'lane',
    'mnr': 'manor',
    'mt': 'mount',
    'mtn': 'mountain',
    'mtns': 'mountains',
    'pk': 'park',
    'pt': 'point',
    'rd': 'road',
    'st': 'street',
};


let inclusionList = ['highway', 'junction'];

let nameTags = ['ref', 'name', 'name:en', 'loc_name', 'nat_name', 'official_name', 'reg_name', 'short_name'];

export {
    sanitizedRoadWords,
    inclusionList,
    nameTags
};
